import type { MbtiType } from './api';

export interface MbtiProfile {
  type: MbtiType;
  label: string;
  nickname: string;
  emoji: string;
  tone: string;
  values: string[];
  overallLens: string;
  loveLens: string;
  moneyLens: string;
  healthLens: string;
  promptStyle: string;
}

export const MBTI_PROFILES: Record<MbtiType, MbtiProfile> = {
  INTJ: {
    type: 'INTJ',
    label: '전략가',
    nickname: '용의주도한 전략가',
    emoji: '🧠',
    tone: '논리적이고 분석적인 말투, 불필요한 감성 배제, 핵심 중심',
    values: ['효율', '장기 계획', '독립성', '깊은 통찰'],
    overallLens: '전략적 관점에서 오늘 하루를 계획하는 방식으로',
    loveLens: '감정보다는 파트너와의 지적 교감과 신뢰 관계 중심으로',
    moneyLens: '장기 투자와 자산 관리 전략 관점에서',
    healthLens: '시스템적이고 루틴 기반의 건강 관리 방식으로',
    promptStyle: '전략적이고 분석적인 어조. "오늘은 전략적으로 접근하면 좋은 날이에요" 같은 표현 사용.',
  },
  INTP: {
    type: 'INTP',
    label: '논리술사',
    nickname: '호기심 많은 사색가',
    emoji: '🔬',
    tone: '지적 호기심을 자극하는 말투, 가능성과 아이디어 중심',
    values: ['지적 탐구', '논리', '창의적 해결', '자유'],
    overallLens: '새로운 가능성을 발견하는 관점에서',
    loveLens: '상대와의 지적 대화와 정신적 교류 중심으로',
    moneyLens: '독창적인 수익 모델이나 효율적 자산 활용 관점에서',
    healthLens: '과학적 근거에 기반한 건강 최적화 방식으로',
    promptStyle: '지적 호기심을 자극하는 어조. "흥미로운 가능성이 열리는 날" 같은 표현 사용.',
  },
  ENTJ: {
    type: 'ENTJ',
    label: '통솔자',
    nickname: '대담한 리더',
    emoji: '👑',
    tone: '자신감 있고 결단력 있는 말투, 목표 달성 중심',
    values: ['리더십', '성과', '효율', '비전'],
    overallLens: '목표를 향해 과감하게 전진하는 관점에서',
    loveLens: '파트너십의 시너지와 함께 성장하는 관계 중심으로',
    moneyLens: '투자 수익률과 재무 목표 달성 관점에서',
    healthLens: '최고의 퍼포먼스를 위한 체력 관리 방식으로',
    promptStyle: '자신감 넘치는 어조. "오늘은 당신이 주도권을 잡을 날" 같은 표현 사용.',
  },
  ENTP: {
    type: 'ENTP',
    label: '변론가',
    nickname: '재기발랄한 발명가',
    emoji: '💡',
    tone: '재치 있고 도전적인 말투, 유머와 기발한 관점',
    values: ['혁신', '논쟁', '자유', '다양한 경험'],
    overallLens: '기존 틀을 깨는 새로운 시도의 관점에서',
    loveLens: '상대와의 유쾌한 대화와 서로의 성장 자극 중심으로',
    moneyLens: '새로운 기회와 창의적 수익 창출 관점에서',
    healthLens: '지루하지 않고 다양한 활동으로 건강을 챙기는 방식으로',
    promptStyle: '재치 있고 도전적인 어조. "오늘은 규칙을 좀 깨볼까요?" 같은 표현 사용.',
  },
  INFJ: {
    type: 'INFJ',
    label: '옹호자',
    nickname: '통찰력 있는 이상주의자',
    emoji: '🌌',
    tone: '따뜻하면서도 깊이 있는 말투, 의미와 가치 중심',
    values: ['의미 있는 삶', '깊은 유대', '직관', '이상 실현'],
    overallLens: '내면의 직관을 따르며 의미를 발견하는 관점에서',
    loveLens: '영혼 깊이 연결되는 진정한 교감 중심으로',
    moneyLens: '가치관에 맞는 의미 있는 소비와 투자 관점에서',
    healthLens: '마음과 몸의 균형을 찾는 총체적 방식으로',
    promptStyle: '따뜻하고 영적인 어조. "오늘은 내면의 목소리에 귀 기울여보세요" 같은 표현 사용.',
  },
  INFP: {
    type: 'INFP',
    label: '중재자',
    nickname: '감성 충만한 치유자',
    emoji: '🦋',
    tone: '시적이고 감성적인 말투, 개인의 가치와 꿈 중심',
    values: ['진정성', '창의성', '공감', '이상'],
    overallLens: '자신만의 가치관으로 세상을 바라보는 관점에서',
    loveLens: '진심으로 교감하는 로맨틱한 관계 중심으로',
    moneyLens: '물질보다 가치를 추구하는 현명한 소비 관점에서',
    healthLens: '감성적 안정과 자기 돌봄을 우선하는 방식으로',
    promptStyle: '시적이고 감성적인 어조. "오늘은 마음이 이끄는 대로 흘러가보세요" 같은 표현 사용.',
  },
  ENFJ: {
    type: 'ENFJ',
    label: '선도자',
    nickname: '카리스마 넘치는 리더',
    emoji: '🌟',
    tone: '따뜻하고 격려하는 말투, 사람 중심',
    values: ['리더십', '공감', '조화', '영감'],
    overallLens: '주변 사람들과 함께 성장하는 관점에서',
    loveLens: '상대를 깊이 이해하고 함께 성장하는 관계 중심으로',
    moneyLens: '나와 주변 모두가 풍요로워지는 투자 관점에서',
    healthLens: '사람들과 함께하는 활동으로 활력을 얻는 방식으로',
    promptStyle: '따뜻하고 격려하는 어조. "당신의 따뜻한 에너지가 빛나는 날이에요" 같은 표현 사용.',
  },
  ENFP: {
    type: 'ENFP',
    label: '활동가',
    nickname: '열정 가득한 자유영혼',
    emoji: '🎨',
    tone: '밝고 열정적인 말투, 가능성과 영감 중심',
    values: ['자유', '창의성', '열정', '새로운 경험'],
    overallLens: '감정의 흐름을 따라 자유롭게 탐험하는 관점에서',
    loveLens: '설레임과 진정성이 공존하는 로맨틱한 관계 중심으로',
    moneyLens: '경험에 투자하는 풍요로운 삶의 관점에서',
    healthLens: '즐기면서 자연스럽게 건강해지는 방식으로',
    promptStyle: '밝고 에너지 넘치는 어조. "오늘은 감정을 따라가도 괜찮아요!" 같은 표현 사용.',
  },
  ISTJ: {
    type: 'ISTJ',
    label: '현실주의자',
    nickname: '믿음직한 관리자',
    emoji: '📋',
    tone: '차분하고 신뢰감 있는 말투, 실용성과 안정 중심',
    values: ['책임감', '안정', '전통', '꼼꼼함'],
    overallLens: '계획에 따라 차근차근 실행하는 관점에서',
    loveLens: '신뢰와 헌신으로 쌓아가는 안정적 관계 중심으로',
    moneyLens: '안정적인 저축과 꼼꼼한 재무 관리 관점에서',
    healthLens: '규칙적인 생활 습관과 꾸준한 관리 방식으로',
    promptStyle: '차분하고 실용적인 어조. "오늘은 계획대로 움직이면 좋은 결과가 있어요" 같은 표현 사용.',
  },
  ISFJ: {
    type: 'ISFJ',
    label: '수호자',
    nickname: '다정한 수호자',
    emoji: '🛡️',
    tone: '따뜻하고 세심한 말투, 배려와 안정 중심',
    values: ['헌신', '배려', '안정', '조화'],
    overallLens: '소중한 사람들을 지키며 따뜻한 하루를 보내는 관점에서',
    loveLens: '상대를 세심하게 챙기는 따뜻한 사랑 중심으로',
    moneyLens: '가족과 소중한 사람을 위한 현명한 소비 관점에서',
    healthLens: '자신도 돌보면서 주변도 챙기는 균형 잡힌 방식으로',
    promptStyle: '따뜻하고 세심한 어조. "주변을 챙기고 싶은 마음이 드는 날, 사주가 그 따뜻함을 응원해요" 같은 표현 사용.',
  },
  ESTJ: {
    type: 'ESTJ',
    label: '경영자',
    nickname: '원칙 있는 실행가',
    emoji: '📊',
    tone: '직접적이고 체계적인 말투, 결과와 실행 중심',
    values: ['질서', '효율', '리더십', '실행력'],
    overallLens: '체계적으로 하루를 관리하고 성과를 내는 관점에서',
    loveLens: '명확한 소통과 실질적인 표현으로 사랑을 보여주는 중심으로',
    moneyLens: '확실한 계획과 실행을 통한 자산 증식 관점에서',
    healthLens: '목표를 세우고 체계적으로 달성하는 관리 방식으로',
    promptStyle: '직접적이고 실행 지향적 어조. "오늘은 주도적으로 움직이면 큰 성과가 있어요" 같은 표현 사용.',
  },
  ESFJ: {
    type: 'ESFJ',
    label: '집정관',
    nickname: '사교적인 외교관',
    emoji: '🤝',
    tone: '상냥하고 사교적인 말투, 관계와 조화 중심',
    values: ['조화', '배려', '사교', '전통'],
    overallLens: '주변 사람들과 조화롭게 어우러지는 관점에서',
    loveLens: '상대의 마음을 잘 읽고 함께 행복해지는 관계 중심으로',
    moneyLens: '사람들과 나누면서 풍요로워지는 소비 관점에서',
    healthLens: '함께하는 활동으로 즐겁게 건강을 지키는 방식으로',
    promptStyle: '상냥하고 배려하는 어조. "오늘은 소중한 사람들과의 시간이 행운을 불러와요" 같은 표현 사용.',
  },
  ISTP: {
    type: 'ISTP',
    label: '장인',
    nickname: '냉철한 해결사',
    emoji: '🔧',
    tone: '간결하고 쿨한 말투, 실용성과 자유 중심',
    values: ['자유', '실용', '즉흥', '효율'],
    overallLens: '유연하게 상황에 대처하는 실용적 관점에서',
    loveLens: '말보다 행동으로 보여주는 쿨한 관계 중심으로',
    moneyLens: '실용적이고 합리적인 소비와 투자 관점에서',
    healthLens: '자유롭고 활동적인 방식으로 건강을 유지하는 방식으로',
    promptStyle: '간결하고 실용적인 어조. "오늘은 몸이 이끄는 대로, 직감을 믿어보세요" 같은 표현 사용.',
  },
  ISFP: {
    type: 'ISFP',
    label: '모험가',
    nickname: '감성적인 예술가',
    emoji: '🎵',
    tone: '부드럽고 감성적인 말투, 아름다움과 현재 중심',
    values: ['자유', '미적 감각', '진정성', '순간'],
    overallLens: '오감으로 오늘의 아름다움을 느끼는 관점에서',
    loveLens: '순수하고 자연스러운 감정의 흐름에 맡기는 관계 중심으로',
    moneyLens: '아름다움과 가치 있는 것에 현명하게 투자하는 관점에서',
    healthLens: '자연 속에서 마음의 평화를 찾는 방식으로',
    promptStyle: '부드럽고 감각적인 어조. "오늘은 작은 것에서 행복을 발견할 수 있는 날이에요" 같은 표현 사용.',
  },
  ESTP: {
    type: 'ESTP',
    label: '사업가',
    nickname: '모험을 즐기는 행동파',
    emoji: '🏄',
    tone: '에너지 넘치고 직접적인 말투, 행동과 즉흥 중심',
    values: ['행동', '즐거움', '도전', '현실감각'],
    overallLens: '적극적으로 기회를 잡는 행동 중심 관점에서',
    loveLens: '대담하게 다가가고 솔직하게 표현하는 관계 중심으로',
    moneyLens: '기회를 빠르게 포착하는 실전형 투자 관점에서',
    healthLens: '액티브한 활동으로 에너지를 충전하는 방식으로',
    promptStyle: '활발하고 직접적인 어조. "오늘은 머뭇거리지 말고 바로 행동하세요!" 같은 표현 사용.',
  },
  ESFP: {
    type: 'ESFP',
    label: '연예인',
    nickname: '무대 위의 자유영혼',
    emoji: '🎭',
    tone: '밝고 재미있는 말투, 즐거움과 현재 중심',
    values: ['즐거움', '자유', '표현', '사람들'],
    overallLens: '오늘을 최대한 즐기며 사는 관점에서',
    loveLens: '함께하는 시간이 빛나는 설레는 관계 중심으로',
    moneyLens: '인생을 즐기면서도 현명하게 쓰는 관점에서',
    healthLens: '즐겁게 춤추듯 활기차게 건강을 지키는 방식으로',
    promptStyle: '밝고 유쾌한 어조. "오늘은 당신이 주인공인 날이에요, 무대를 즐기세요!" 같은 표현 사용.',
  },
};

export function getMbtiProfile(mbti: MbtiType): MbtiProfile {
  return MBTI_PROFILES[mbti];
}

/** MBTI 그룹 (결과 화면에서 유형 분류용) */
export function getMbtiGroup(mbti: MbtiType): string {
  const groups: Record<string, string> = {
    INTJ: '분석형 (NT)',
    INTP: '분석형 (NT)',
    ENTJ: '분석형 (NT)',
    ENTP: '분석형 (NT)',
    INFJ: '이상형 (NF)',
    INFP: '이상형 (NF)',
    ENFJ: '이상형 (NF)',
    ENFP: '이상형 (NF)',
    ISTJ: '안정형 (SJ)',
    ISFJ: '안정형 (SJ)',
    ESTJ: '안정형 (SJ)',
    ESFJ: '안정형 (SJ)',
    ISTP: '탐험형 (SP)',
    ISFP: '탐험형 (SP)',
    ESTP: '탐험형 (SP)',
    ESFP: '탐험형 (SP)',
  };
  return groups[mbti] ?? '';
}
